PRAGMA foreign_keys = ON;

CREATE TABLE users (id TEXT PRIMARY KEY NOT NULL, auth_subject TEXT NOT NULL UNIQUE, email TEXT NOT NULL, display_name TEXT, locale TEXT DEFAULT 'en' NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, deletion_scheduled_at INTEGER);
CREATE INDEX users_email_idx ON users(email);
CREATE TABLE profiles (user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE, headline TEXT, summary TEXT, verified_facts_json TEXT DEFAULT '[]' NOT NULL, preferences_json TEXT DEFAULT '{}' NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE job_targets (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL, company TEXT, job_description TEXT, competencies_json TEXT DEFAULT '[]' NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX job_targets_owner_idx ON job_targets(user_id, updated_at);
CREATE TABLE documents (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind TEXT NOT NULL, file_name TEXT NOT NULL, content_type TEXT NOT NULL, object_key TEXT NOT NULL UNIQUE, size_bytes INTEGER NOT NULL, sha256 TEXT NOT NULL, parse_status TEXT DEFAULT 'pending' NOT NULL, extracted_text TEXT, verified_facts_json TEXT DEFAULT '[]' NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX documents_owner_idx ON documents(user_id, created_at);
CREATE TABLE sessions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, job_target_id TEXT REFERENCES job_targets(id) ON DELETE SET NULL, device_id TEXT NOT NULL, mode TEXT NOT NULL, locale TEXT NOT NULL, status TEXT DEFAULT 'created' NOT NULL, retention_choice TEXT NOT NULL, started_at INTEGER NOT NULL, ended_at INTEGER, discarded_at INTEGER, saved_at INTEGER, live_seconds INTEGER DEFAULT 0 NOT NULL, report_id TEXT);
CREATE INDEX sessions_owner_idx ON sessions(user_id, started_at);
CREATE INDEX sessions_status_idx ON sessions(status, started_at);
CREATE TABLE transcript_segments (id TEXT PRIMARY KEY NOT NULL, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, speaker TEXT NOT NULL, text TEXT NOT NULL, started_at_ms INTEGER NOT NULL, ended_at_ms INTEGER NOT NULL, item_id TEXT, created_at INTEGER NOT NULL);
CREATE INDEX segments_timeline_idx ON transcript_segments(session_id, started_at_ms);
CREATE TABLE suggestions (id TEXT PRIMARY KEY NOT NULL, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, question TEXT NOT NULL, response_json TEXT NOT NULL, model TEXT NOT NULL, grounded INTEGER NOT NULL, latency_ms INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX suggestions_session_idx ON suggestions(session_id, created_at);
CREATE TABLE reports (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_id TEXT NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE, score REAL, summary TEXT NOT NULL, strengths_json TEXT DEFAULT '[]' NOT NULL, improvements_json TEXT DEFAULT '[]' NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX reports_owner_idx ON reports(user_id, created_at);
CREATE TABLE consent_receipts (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE, policy_version TEXT NOT NULL, recording_allowed INTEGER NOT NULL, ai_assistance_allowed INTEGER NOT NULL, ip_hash TEXT, created_at INTEGER NOT NULL);
CREATE TABLE entitlements (user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE, plan TEXT DEFAULT 'free' NOT NULL, status TEXT DEFAULT 'active' NOT NULL, source TEXT DEFAULT 'system' NOT NULL, source_customer_id TEXT, source_subscription_id TEXT, current_period_end INTEGER, updated_at INTEGER NOT NULL);
CREATE TABLE usage_ledger (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, period_key TEXT NOT NULL, live_seconds INTEGER DEFAULT 0 NOT NULL, mock_sessions INTEGER DEFAULT 0 NOT NULL, reason TEXT NOT NULL, external_ref TEXT, created_at INTEGER NOT NULL);
CREATE INDEX usage_period_idx ON usage_ledger(user_id, period_key);
CREATE UNIQUE INDEX usage_external_ref_idx ON usage_ledger(external_ref);
CREATE TABLE devices (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, platform TEXT NOT NULL, name TEXT, app_version TEXT, last_seen_at INTEGER NOT NULL, revoked_at INTEGER);
CREATE INDEX devices_owner_idx ON devices(user_id, last_seen_at);
CREATE TABLE audit_events (id TEXT PRIMARY KEY NOT NULL, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT, metadata_json TEXT DEFAULT '{}' NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX audit_owner_idx ON audit_events(user_id, created_at);
CREATE TABLE webhook_events (id TEXT PRIMARY KEY NOT NULL, provider TEXT NOT NULL, event_id TEXT NOT NULL, payload_hash TEXT NOT NULL, status TEXT NOT NULL, processed_at INTEGER NOT NULL);
CREATE UNIQUE INDEX webhook_provider_event_idx ON webhook_events(provider, event_id);
CREATE TABLE upload_tickets (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, document_id TEXT NOT NULL, object_key TEXT NOT NULL, expires_at INTEGER NOT NULL, consumed_at INTEGER);
CREATE INDEX upload_ticket_expiry_idx ON upload_tickets(expires_at);
CREATE TABLE deletion_requests (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL, requested_at INTEGER NOT NULL, execute_after INTEGER NOT NULL, completed_at INTEGER);
CREATE INDEX deletion_status_idx ON deletion_requests(status, execute_after);
CREATE TABLE rate_limit_windows (key TEXT PRIMARY KEY NOT NULL, window_started_at INTEGER NOT NULL, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX rate_limit_expiry_idx ON rate_limit_windows(expires_at);
