import React from 'react';
import { FlatList, Keyboard, KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from 'react-native';
import { assistantActions, formatSessionTime } from '@interview-copilot/sdk';
import type { useMeetingSession } from './use-meeting-session';
import { Action, Empty, Failure, palette, ui } from './ui';

export function MobileLiveSession({ session, onBack, onEnd }: { session: ReturnType<typeof useMeetingSession>; onBack: () => void; onEnd: () => void }) {
  const [tab, setTab] = React.useState<'chat' | 'transcript'>('chat');
  const [prompt, setPrompt] = React.useState('');
  const [follow, setFollow] = React.useState(true);
  const [keyboardOpen, setKeyboardOpen] = React.useState(false);
  React.useEffect(() => {
    const show = Keyboard.addListener('keyboardDidShow', () => setKeyboardOpen(true));
    const hide = Keyboard.addListener('keyboardDidHide', () => setKeyboardOpen(false));
    return () => { show.remove(); hide.remove(); };
  }, []);
  const transcriptList = React.useRef<FlatList>(null);
  const busy = ['starting', 'processing'].includes(session.state);
  const status = session.state === 'recording' ? 'Recording room audio' : session.state === 'starting' ? 'Connecting microphone…' : session.state === 'processing' ? 'Saving your conversation…' : session.state === 'error' ? 'Needs attention · audio stopped' : 'Recording paused';
  function submit() { if (prompt.trim().length >= 2) { void session.ask(prompt.trim()); setPrompt(''); Keyboard.dismiss(); } }
  return <KeyboardAvoidingView style={ui.screen} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={ui.header}><Action secondary onPress={onBack}>Notes</Action><View style={{ alignItems: 'flex-end', flex: 1 }}><Text style={[ui.title, { fontVariant: ['tabular-nums'] }]}>{formatSessionTime(session.seconds)}</Text><Text accessibilityLiveRegion="polite" style={[ui.metadata, { color: session.state === 'recording' ? palette.recording : palette.secondary }]}>{status}</Text></View></View>
    <Failure text={session.error} /><View style={{ paddingHorizontal: 22, paddingBottom: 14 }}><Text numberOfLines={2} style={[ui.sectionTitle, { fontSize: 16 }]}>{session.title || 'New conversation'}</Text><Text style={ui.metadata}>{session.state === 'recording' ? session.speaking ? '▂ ▆ █ ▆ ▂  Speech detected' : '· · · · ·  Waiting for speech' : 'Microphone stopped'}</Text><View style={ui.tabs}>{(['chat', 'transcript'] as const).map(item => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: tab === item }} style={[ui.tab, tab === item && ui.tabActive]} onPress={() => setTab(item)}><Text style={[ui.tabText, tab === item && ui.tabTextActive]}>{item === 'chat' ? 'AI chat' : 'Transcript'}</Text></Pressable>)}</View></View>
    {tab === 'chat' ? <FlatList data={session.interactions} keyExtractor={item => item.id} keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingHorizontal: 22, gap: 18, paddingBottom: 16, flexGrow: 1 }} renderItem={({ item }) => <View style={{ gap: 10 }}><Text selectable style={[ui.copy, { textAlign: 'right' }]}>{item.question}</Text><View style={ui.card}><Text style={ui.eyebrow}>TORVI</Text><Text selectable style={{ color: palette.text, fontSize: 16, lineHeight: 26 }}>{item.answer}</Text></View></View>} ListEmptyComponent={<Empty title="Stay in the conversation." copy="Tap Assist for a useful next response, or ask anything about what has been said." />} ListFooterComponent={session.asking ? <Text accessibilityLiveRegion="polite" style={ui.copy}>Torvi is preparing a response…</Text> : undefined} /> : <FlatList ref={transcriptList} data={session.segments} keyExtractor={item => item.id} contentContainerStyle={{ paddingHorizontal: 22, paddingBottom: 16, flexGrow: 1 }} onScrollBeginDrag={() => setFollow(false)} onContentSizeChange={() => { if (follow) transcriptList.current?.scrollToEnd({ animated: false }); }} renderItem={({ item }) => <View style={{ paddingVertical: 16, borderBottomWidth: 1, borderColor: palette.border }}><Text style={ui.metadata}>Room audio · {formatSessionTime(item.startedAtMs / 1000)}</Text><Text selectable style={[ui.copy, { color: palette.text, marginTop: 6 }]}>{item.text}</Text></View>} ListEmptyComponent={<Empty title="Listening for the first words." copy="Final transcript segments appear here. Room audio does not identify individual speakers." />} />}
    {tab === 'transcript' && !follow && <Action secondary onPress={() => { setFollow(true); transcriptList.current?.scrollToEnd({ animated: false }); }}>Jump to latest</Action>}
    <View style={ui.dock}>{tab === 'chat' && <>{!keyboardOpen && <><View style={ui.tabs}>{(['adaptive', 'bullets', 'paragraph'] as const).map(style => <Pressable key={style} accessibilityRole="button" accessibilityState={{ selected: session.responseStyle === style }} onPress={() => session.setResponseStyle(style)} style={[ui.tab, session.responseStyle === style && ui.tabActive]}><Text style={ui.tabText}>{style === 'bullets' ? 'Points' : style === 'paragraph' ? 'Paragraph' : 'Adaptive'}</Text></Pressable>)}</View><View style={ui.row}><Action disabled={session.asking || busy || !session.sessionId} onPress={() => void session.ask()}>✦ Assist</Action><Action secondary disabled={session.asking || busy || !session.sessionId} onPress={() => void session.ask(assistantActions[1].prompt)}>What should I say?</Action><Action secondary disabled={session.asking || busy || !session.sessionId} onPress={() => void session.ask(assistantActions[3].prompt)}>Recap</Action></View></>}<View style={{ flexDirection: 'row', gap: 8 }}><TextInput accessibilityLabel="Ask about this meeting" style={[ui.input, { flex: 1, maxHeight: 100 }]} placeholder="Ask about this meeting…" placeholderTextColor={palette.tertiary} value={prompt} onChangeText={setPrompt} maxLength={8000} multiline /><Action disabled={prompt.trim().length < 2 || session.asking || busy || !session.sessionId} onPress={submit}>Send</Action></View></>}
      <View style={ui.row}><View style={{ flex: 1 }}><Action secondary disabled={busy || session.ended} onPress={session.state === 'recording' ? session.pause : () => void session.start()}>{session.state === 'recording' ? 'Pause' : 'Resume'}</Action></View><View style={{ flex: 1 }}><Action secondary disabled={busy || !session.sessionId} onPress={onEnd}>{session.state === 'processing' ? 'Saving…' : 'End session'}</Action></View></View></View>
  </KeyboardAvoidingView>;
}
